export interface HiraganaLetter {
  hiragana: string;
  romanji: string;
  letter: string;
}

const hiragana: HiraganaLetter[] = [
  { hiragana: "あ", romanji: "a", letter: "vowel" },
  { hiragana: "い", romanji: "i", letter: "vowel" },
  { hiragana: "う", romanji: "u", letter: "vowel" },
  { hiragana: "え", romanji: "e", letter: "vowel" },
  { hiragana: "お", romanji: "o", letter: "vowel" },
  { hiragana: "か", romanji: "ka", letter: "k" },
  { hiragana: "き", romanji: "ki", letter: "k" },
  { hiragana: "く", romanji: "ku", letter: "k" },
  { hiragana: "け", romanji: "ke", letter: "k" },
  { hiragana: "こ", romanji: "ko", letter: "k" },
  { hiragana: "さ", romanji: "sa", letter: "s" },
  { hiragana: "し", romanji: "shi", letter: "s" },
  { hiragana: "す", romanji: "su", letter: "s" },
  { hiragana: "せ", romanji: "se", letter: "s" },
  { hiragana: "そ", romanji: "so", letter: "s" },
  { hiragana: "た", romanji: "ta", letter: "t" },
  { hiragana: "ち", romanji: "chi", letter: "t" },
  { hiragana: "つ", romanji: "tsu", letter: "t" },
  { hiragana: "て", romanji: "te", letter: "t" },
  { hiragana: "と", romanji: "to", letter: "t" },
  { hiragana: "な", romanji: "na", letter: "n" },
  { hiragana: "に", romanji: "ni", letter: "n" },
  { hiragana: "ぬ", romanji: "nu", letter: "n" },
  { hiragana: "ね", romanji: "ne", letter: "n" },
  { hiragana: "の", romanji: "no", letter: "n" },
  { hiragana: "は", romanji: "ha", letter: "h" },
  { hiragana: "ひ", romanji: "hi", letter: "h" },
  { hiragana: "ふ", romanji: "fu", letter: "h" },
  { hiragana: "へ", romanji: "he", letter: "h" },
  { hiragana: "ほ", romanji: "ho", letter: "h" },
  { hiragana: "ま", romanji: "ma", letter: "m" },
  { hiragana: "み", romanji: "mi", letter: "m" },
  { hiragana: "む", romanji: "mu", letter: "m" },
  { hiragana: "め", romanji: "me", letter: "m" },
  { hiragana: "も", romanji: "mo", letter: "m" },
  { hiragana: "や", romanji: "ya", letter: "y" },
  { hiragana: "ゆ", romanji: "yu", letter: "y" },
  { hiragana: "よ", romanji: "yo", letter: "y" },
  { hiragana: "ら", romanji: "ra", letter: "r" },
  { hiragana: "り", romanji: "ri", letter: "r" },
  { hiragana: "る", romanji: "ru", letter: "r" },
  { hiragana: "れ", romanji: "re", letter: "r" },
  { hiragana: "ろ", romanji: "ro", letter: "r" },
  { hiragana: "わ", romanji: "wa", letter: "w" },
  { hiragana: "を", romanji: "wo", letter: "w" },
  { hiragana: "ん", romanji: "n", letter: "n" },
  { hiragana: "が", romanji: "ga", letter: "g" },
  { hiragana: "ぎ", romanji: "gi", letter: "g" },
  { hiragana: "ぐ", romanji: "gu", letter: "g" },
  { hiragana: "げ", romanji: "ge", letter: "g" },
  { hiragana: "ご", romanji: "go", letter: "g" },
  { hiragana: "ざ", romanji: "za", letter: "z" },
  { hiragana: "じ", romanji: "ji", letter: "z" },
  { hiragana: "ず", romanji: "zu", letter: "z" },
  { hiragana: "ぜ", romanji: "ze", letter: "z" },
  { hiragana: "ぞ", romanji: "zo", letter: "z" },
  { hiragana: "だ", romanji: "da", letter: "d" },
  { hiragana: "ぢ", romanji: "ji", letter: "d" },
  { hiragana: "づ", romanji: "zu", letter: "d" },
  { hiragana: "で", romanji: "de", letter: "d" },
  { hiragana: "ど", romanji: "do", letter: "d" },
  { hiragana: "ば", romanji: "ba", letter: "b" },
  { hiragana: "び", romanji: "bi", letter: "b" },
  { hiragana: "ぶ", romanji: "bu", letter: "b" },
  { hiragana: "べ", romanji: "be", letter: "b" },
  { hiragana: "ぼ", romanji: "bo", letter: "b" },
  { hiragana: "ぱ", romanji: "pa", letter: "p" },
  { hiragana: "ぴ", romanji: "pi", letter: "p" },
  { hiragana: "ぷ", romanji: "pu", letter: "p" },
  { hiragana: "ぺ", romanji: "pe", letter: "p" },
  { hiragana: "ぽ", romanji: "po", letter: "p" },
];

export default hiragana;