export interface KatakanaLetter {
    katakana: string;
    romanji: string;
    type: string;
  }
  
  const katakana: KatakanaLetter[] = [
    { katakana: "ア", romanji: "a", type: "vowel" },
    { katakana: "イ", romanji: "i", type: "vowel" },
    { katakana: "ウ", romanji: "u", type: "vowel" },
    { katakana: "エ", romanji: "e", type: "vowel" },
    { katakana: "オ", romanji: "o", type: "vowel" },
    { katakana: "カ", romanji: "ka", type: "k" },
    { katakana: "キ", romanji: "ki", type: "k" },
    { katakana: "ク", romanji: "ku", type: "k" },
    { katakana: "ケ", romanji: "ke", type: "k" },
    { katakana: "コ", romanji: "ko", type: "k" },
    { katakana: "サ", romanji: "sa", type: "s" },
    { katakana: "シ", romanji: "shi", type: "s" },
    { katakana: "ス", romanji: "su", type: "s" },
    { katakana: "セ", romanji: "se", type: "s" },
    { katakana: "ソ", romanji: "so", type: "s" },
    { katakana: "タ", romanji: "ta", type: "t" },
    { katakana: "チ", romanji: "chi", type: "t" },
    { katakana: "ツ", romanji: "tsu", type: "t" },
    { katakana: "テ", romanji: "te", type: "t" },
    { katakana: "ト", romanji: "to", type: "t" },
    { katakana: "ナ", romanji: "na", type: "n" },
    { katakana: "ニ", romanji: "ni", type: "n" },
    { katakana: "ヌ", romanji: "nu", type: "n" },
    { katakana: "ネ", romanji: "ne", type: "n" },
    { katakana: "ノ", romanji: "no", type: "n" },
    { katakana: "ハ", romanji: "ha", type: "h" },
    { katakana: "ヒ", romanji: "hi", type: "h" },
    { katakana: "フ", romanji: "fu", type: "h" },
    { katakana: "ヘ", romanji: "he", type: "h" },
    { katakana: "ホ", romanji: "ho", type: "h" },
    { katakana: "マ", romanji: "ma", type: "m" },
    { katakana: "ミ", romanji: "mi", type: "m" },
    { katakana: "ム", romanji: "mu", type: "m" },
    { katakana: "メ", romanji: "me", type: "m" },
    { katakana: "モ", romanji: "mo", type: "m" },
    { katakana: "ヤ", romanji: "ya", type: "y" },
    { katakana: "ユ", romanji: "yu", type: "y" },
    { katakana: "ヨ", romanji: "yo", type: "y" },
    { katakana: "ラ", romanji: "ra", type: "r" },
    { katakana: "リ", romanji: "ri", type: "r" },
    { katakana: "ル", romanji: "ru", type: "r" },
    { katakana: "レ", romanji: "re", type: "r" },
    { katakana: "ロ", romanji: "ro", type: "r" },
    { katakana: "ワ", romanji: "wa", type: "w" },
    { katakana: "ヲ", romanji: "wo", type: "w" },
    { katakana: "ン", romanji: "n", type: "n" },
    { katakana: "ガ", romanji: "ga", type: "g" },
    { katakana: "ギ", romanji: "gi", type: "g" },
    { katakana: "グ", romanji: "gu", type: "g" },
    { katakana: "ゲ", romanji: "ge", type: "g" },
    { katakana: "ゴ", romanji: "go", type: "g" },
    { katakana: "ザ", romanji: "za", type: "z" },
    { katakana: "ジ", romanji: "ji", type: "z" },
    { katakana: "ズ", romanji: "zu", type: "z" },
    { katakana: "ゼ", romanji: "ze", type: "z" },
    { katakana: "ゾ", romanji: "zo", type: "z" },
    { katakana: "ダ", romanji: "da", type: "d" },
    { katakana: "ヂ", romanji: "ji", type: "d" },
    { katakana: "ヅ", romanji: "zu", type: "d" },
    { katakana: "デ", romanji: "de", type: "d" },
    { katakana: "ド", romanji: "do", type: "d" },
    { katakana: "バ", romanji: "ba", type: "b" },
    { katakana: "ビ", romanji: "bi", type: "b" },
    { katakana: "ブ", romanji: "bu", type: "b" },
    { katakana: "ベ", romanji: "be", type: "b" },
    { katakana: "ボ", romanji: "bo", type: "b" },
    { katakana: "パ", romanji: "pa", type: "p" },
    { katakana: "ピ", romanji: "pi", type: "p" },
    { katakana: "プ", romanji: "pu", type: "p" },
    { katakana: "ペ", romanji: "pe", type: "p" },
    { katakana: "ポ", romanji: "po", type: "p" },
  ];
  
  export default katakana;
  